import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f3f4f6', alignItems: 'center', justifyContent: 'center', padding: 20, paddingTop: 60 },
  titlu: { fontSize: 24, fontWeight: 'bold', color: '#111827', marginBottom: 2 },
  subtitlu: { fontSize: 13, color: '#6b7280', marginBottom: 20, textAlign: 'center' },
  dashboardContainer: { width: '100%', flex: 1 },
  card: { backgroundColor: '#fff', padding: 16, borderRadius: 16, width: '100%', marginBottom: 12, borderWidth: 1, borderColor: '#e5e7eb', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2 },
  statsCard: { backgroundColor: '#1e293b', padding: 16, borderRadius: 16, width: '100%', marginBottom: 15 },
  statsLabel: { color: '#94a3b8', fontSize: 11, fontWeight: 'bold', textTransform: 'uppercase' },
  statsNumar: { color: '#f8fafc', fontSize: 20, fontWeight: 'bold', marginTop: 5 },
  statsSubtext: { color: '#64748b', fontSize: 11, marginTop: 4 },
  statusCard: { width: '100%', padding: 10, backgroundColor: '#eff6ff', borderRadius: 8, marginBottom: 12 },
  statusLabel: { fontSize: 11, color: '#9ca3af', fontWeight: 'bold', textTransform: 'uppercase', marginBottom: 6 },
  sectiuneTitlu: { fontSize: 14, fontWeight: 'bold', color: '#374151', marginBottom: 8, marginTop: 5, alignSelf: 'flex-start' },
  input: { width: '100%', height: 45, borderWidth: 1, borderColor: '#d1d5db', borderRadius: 8, paddingHorizontal: 10, fontSize: 14, marginBottom: 10, backgroundColor: '#f9fafb', color: '#111827' },
  numeText: { fontSize: 18, fontWeight: 'bold', color: '#111827', marginBottom: 8 },
  detaliuText: { fontSize: 13, color: '#4b5563', marginBottom: 4 },
  statusText: { fontSize: 12, color: '#1d4ed8', fontWeight: '500', textAlign: 'center' },
  logCard: { backgroundColor: '#fff', width: '100%', padding: 12, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: '#f3f4f6' },
  logHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  badge: { fontSize: 10, fontWeight: 'bold', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, overflow: 'hidden' },
  badgeIntrare: { backgroundColor: '#dcfce7', color: '#15803d' },
  badgeIesire: { backgroundColor: '#fef3c7', color: '#b45309' },
  gateText: { fontSize: 12, color: '#4b5563', fontWeight: '500', marginLeft: 'auto' },
  notesText: { fontSize: 12, color: '#111827' },
  statusOkText: { fontSize: 11, color: '#059669', marginTop: 4, fontWeight: '500' },
  butonLogin: { backgroundColor: '#10b981', paddingVertical: 12, borderRadius: 8, width: '100%', alignItems: 'center', marginTop: 5 },
  butonAcces: { backgroundColor: '#2563eb', paddingVertical: 15, borderRadius: 12, width: '100%', alignItems: 'center', shadowColor: '#2563eb', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 5 },
  butonDezactivat: { backgroundColor: '#9ca3af', opacity: 0.6 },
  butonText: { color: '#fff', fontSize: 15, fontWeight: 'bold' },
});